# Site settings
title: Thought Pieces
header-img: img/home-bg.png
email: sdklos@gmail.com
copyright_name: sdklos
description: > # this means to ignore newlines until "baseurl:"
  a blog about learning and technology
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sdklos
learn_profile: sdklos
email_username: sdklos@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
